# ~/.circleci/config.yml
version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:12
    steps:
      - checkout

      # Restore dependencies from cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      # Install project dependencies
      - run: 
          name: Install dependencies
          command: npm i
      # Cache local dependencies if they don't exist
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Build
          command: npm run build
      - add_ssh_keys:
          fingerprints:
            - "27:33:15:d3:fd:f6:48:43:f6:b2:1b:d0:05:6c:e7:cd"
      - run: 
          name: Deploy
          command: |
            git config --global user.email "${GIT_AUTHOR_EMAIL}"
            git config --global user.name "${GIT_AUTHOR_NAME}"
            npm run deploy

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
